"""initial schema

Revision ID: 27e21941c867
Revises: 
Create Date: 2026-06-28 13:06:16.861381

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e21941c867'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rubro_principal', sa.String(length=128), nullable=False),
    sa.Column('rubro_secundario', sa.String(length=255), nullable=False),
    sa.Column('rubro_final', sa.String(length=255), nullable=False),
    sa.Column('is_seasonal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_audit_user_time', 'audit_log', ['user_id', 'timestamp'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('default_currency', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rubros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('criterio', sa.String(length=16), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_rubro_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lodges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('excel_template', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rubro_accounts',
    sa.Column('rubro_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.code'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rubro_id', 'account_code')
    )
    op.create_table('user_regions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'region_id')
    )
    op.create_table('movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lodge_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_local', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subdiario', sa.String(length=32), nullable=True),
    sa.Column('comprobante', sa.String(length=64), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=32), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('void', sa.Boolean(), nullable=False),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_code'], ['accounts.code'], ),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movements_active', 'movements', ['lodge_id', 'date'], unique=False, postgresql_where=sa.text('NOT void'))
    op.create_index('ix_movements_date', 'movements', ['date'], unique=False)
    op.create_index('ix_movements_lodge_acc_date', 'movements', ['lodge_id', 'account_code', 'date'], unique=False)
    op.create_index('ix_movements_lodge_date', 'movements', ['lodge_id', 'date'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lodge_id', sa.UUID(), nullable=False),
    sa.Column('rubro_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lodge_id', sa.UUID(), nullable=False),
    sa.Column('year_start', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('bn_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fd_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pax_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fx_budget', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lodge_id', 'year_start', name='uq_season_lodge_year')
    )
    op.create_table('user_lodges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lodge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lodge_id'], ['lodges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'lodge_id')
    )
    op.create_table('budget_lines',
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('rubro_id', sa.UUID(), nullable=False),
    sa.Column('budget_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_per_bn', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubros.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('season_id', 'rubro_id')
    )
    op.create_table('season_months',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('bn_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pax_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fd_real', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'year', 'month', name='uq_season_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_months')
    op.drop_table('budget_lines')
    op.drop_table('user_lodges')
    op.drop_table('seasons')
    op.drop_table('observations')
    op.drop_index('ix_movements_lodge_date', table_name='movements')
    op.drop_index('ix_movements_lodge_acc_date', table_name='movements')
    op.drop_index('ix_movements_date', table_name='movements')
    op.drop_index('ix_movements_active', table_name='movements', postgresql_where=sa.text('NOT void'))
    op.drop_table('movements')
    op.drop_table('user_regions')
    op.drop_table('rubro_accounts')
    op.drop_table('lodges')
    op.drop_table('users')
    op.drop_table('rubros')
    op.drop_table('regions')
    op.drop_index('ix_audit_user_time', table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('accounts')
    # ### end Alembic commands ###
