"""season: bn_real_std + months elapsed

Revision ID: 5c4a473fddbd
Revises: 27e21941c867
Create Date: 2026-06-28 13:27:13.409883

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4a473fddbd'
down_revision: Union[str, None] = '27e21941c867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('bn_real_std', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('seasons', sa.Column('pax_real_std', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('seasons', sa.Column('fd_real_std', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('seasons', sa.Column('months_elapsed', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('seasons', sa.Column('months_total', sa.Numeric(precision=4, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'months_total')
    op.drop_column('seasons', 'months_elapsed')
    op.drop_column('seasons', 'fd_real_std')
    op.drop_column('seasons', 'pax_real_std')
    op.drop_column('seasons', 'bn_real_std')
    # ### end Alembic commands ###
